### ISSUE TITLE
MSVC2015 support

### ISSUE THREAD

**Issue by hia3** [OlafvdSpek/ctemplate#117]
Hello!

Any plans on supporting MSVC2015 that was released recently?

It currently does not compile because `<hash_map>`/`<hash_set>` are deprecated and snprintf is (finally) implemented.

**Comment by OlafvdSpek** [comment]
How does snprintf stop it from compiling? Redefinition?
The hash_map deprecation warnings can easily be disabled. ;)

**Comment by hia3** [comment]
Yes, redefinition.
I know, but unordered_* is better. :-)

**Comment by Zitrax** [comment]
Is it supposed to work with VC2013? I am seeing a lot of errors. Or are there binaries somewhere ? (I just need to be able to link another project).

**Comment by OlafvdSpek** [comment]
Yes

**Comment by kyocwn** [comment]
It's relatively easy to solve the problem of deprecated <hash_map>/<hash_set> and redefinition of snprintf. However, I run into other problems when open the original VC7.1 solution in VS2015. After conversion, when I build project libctemplate, I find some other problems as follows:
a. error C3861: 'find_ptr0': identifier not found
b. error C2065: 'JSPARSER_NUM_STATES': undeclared identifier
c. error C2065: 'htmlparser_states_external': undeclared identifier

Can someone give me some guides on how to fix the issues above using VS2015?


Thanks,
Frank

**Comment by OlafvdSpek** [comment]
Frank, what zip archive are you using?

**Comment by kyocwn** [comment]
I click "Download Zip" in the "Code" page to get the source code.

**Comment by OlafvdSpek** [comment]
Try http://xwis.net/ctemplate/ctemplate-2.3.zip

I should really fix the README..

**Comment by kyocwn** [comment]
Thanks Olavfvd! 

Now I can successfully built  libctemplate project using VS2015! 

Is the code here a bit out-of-date?

**Comment by OlafvdSpek** [comment]
No, some auto-generated code isn't in VCS but it can't be generated easily on Windows as it requires Python etc.
