### ISSUE TITLE
README missing autogen.sh step for Compilation

### ISSUE THREAD

**Issue by Vincent-M** [OlafvdSpek/ctemplate#122]
I thought the ./configure file was missing but then I found these steps in configure.ac :

**Comment by OlafvdSpek** [comment]
What if you run autogen.sh first?

**Comment by Vincent-M** [comment]
yes, sorry I'm not familiar with autoconf, 
after running ./autogen.sh everything works fine :)

**Comment by 21plus** [comment]
when running ./autogen.sh, errors occurs as below,
error: possibly undefined macro: AM_SILENT_RULES

**Comment by OlafvdSpek** [comment]
What platform / version?
