### ISSUE TITLE
python2 does not work with Mac with src/htmlparser/generate_fsm.py

### ISSUE THREAD

**Issue by sroycode** [OlafvdSpek/ctemplate#123]
python2 does not work ( using Macports / clang ) but changing to this works
# !/usr/bin/env python2.7

Reference: https://github.com/OlafvdSpek/ctemplate/blob/master/src/htmlparser/generate_fsm.py

**Comment by OlafvdSpek** [comment]
I meant a report to python for python2 not working. ;)

What solution do you propose? What if 2.6 or 2.8 is available but not 2.7?

**Comment by sroycode** [comment]
`which python2 python2.9 python2.8 python2.7 python2.6`

very dirty !!

**Comment by OlafvdSpek** [comment]
Python 3 should now work as well.

**Comment by pinotree** [comment]
Hi @sroycode , I just submitted a series to switch to Python 3, and the change required looks like it might fix the issue you faced too.
See #139 -- can you please test it on top of ce1b8fe617bc052c1d9bf0be6000ead2fd205c6b and 4b7e6c52dc7cbb4d51c9abcebcbac91ec256a62b? Thanks!
