### ISSUE TITLE
Macro Redefinition and Header Conflicts Causes Issue Installing

### ISSUE THREAD

**Issue by atkawa7** [OlafvdSpek/ctemplate#127]
I am using [vcpkg](https://github.com/Microsoft/vcpkg) on windows whenever I try to install `glog`

```
vcpkg install glog
``` 
I get macro redefinition  errors. The issue is caused by two google projects `ctemplate` and `glog` which use same macros for different purposes.  See this line. 

https://github.com/OlafvdSpek/ctemplate/blob/master/src/windows/config.h#L19

```cpp
#define GOOGLE_NAMESPACE  ctemplate
```

and  on this https://github.com/google/glog/blob/master/src/windows/config.h#L4

```cpp
#define GOOGLE_NAMESPACE  google
```

see issue microsoft/vcpkg#1514

**Comment by OlafvdSpek** [comment]
Oops. What if you remove the #define?

**Comment by OlafvdSpek** [comment]
I'm confused, isn't config.h a private header?

**Comment by atkawa7** [comment]
@OlafvdSpek Thanks for the response. So if the config.h is a private header it shouldn't be installed right? However there are other public headers dependent on `config.h` being present

https://github.com/OlafvdSpek/ctemplate/blob/master/src/htmlparser/jsparser.h#L37

https://github.com/OlafvdSpek/ctemplate/blob/master/src/htmlparser/jsparser.h#L37

**Comment by OlafvdSpek** [comment]
I think only the headers in https://github.com/OlafvdSpek/ctemplate/tree/master/src/ctemplate are supposed to be installed / public.

**Comment by atkawa7** [comment]
@OlafvdSpek  I see. Thanks.
