### ISSUE TITLE
Include files *_fsm.h not exist

### ISSUE THREAD

**Issue by Fxztam** [OlafvdSpek/ctemplate#128]
I am trying a build with VS C++ 2015 and getting:

Cannot open include file: 'htmlparser/**jsparser_fsm.h**'_: No such file or directory	libctemplate	..\ctemplate-master\ctemplate-master\src\htmlparser\ **jsparser.cc**  **56**	

Cannot open include file: 'htmlparser/**htmlparser_fsm.h**': No such file or directory	libctemplate	..\ctemplate-master\ctemplate-master\src\htmlparser\ **htmlparser.cc**  **62**	

Thanks.

**Comment by OlafvdSpek** [comment]
Have you tried https://github.com/Microsoft/vcpkg?

If that's not an option, try https://xwis.net/ctemplate/ctemplate-2.3.zip

**Comment by Fxztam** [comment]
No, i tried a simple build of libctemplate ..
and getting now errors from _ctemplate-2.3.zip_ ..

Error	C2375	'snprintf': redefinition; different linkage	libctemplate	..\ctemplate-2.3\ctemplate-2.3\src\windows\port.h	104	

Error	C2440	'initializing': cannot convert from 'int (__cdecl *)(char *const ,const std::size_t,const char *const ,...)' to 'int'	libctemplate	..\ctemplate-2.3\src\template_dictionary.cc	442

**Comment by OlafvdSpek** [comment]
You might want to give vcpkg a try, it's great for other libs as well.

I'll see if a new release is necessary for VS2015.

**Comment by Fxztam** [comment]
Yes, vcpkg works fine !

Thank you, Olaf.

**Comment by scott323** [comment]
you need to generate the FSMs (finite state machines), and you need python for that
example generate script (i used this, requires cygwin w/python):

```
#!/bin/bash
cd src/htmlparser
./generate_fsm.py htmlparser_fsm.config > htmlparser_fsm.h
./generate_fsm.py jsparser_fsm.config > jsparser_fsm.h
./generate_fsm.py ../tests/statemachine_test_fsm.config > ../tests/statemachine_test_fsm.h

```
