### ISSUE TITLE
Libtool library used but 'LIBTOOL' is undefined

### ISSUE THREAD

**Issue by cheiio** [OlafvdSpek/ctemplate#132]
when executing ./autogen.sh I get the following error message:

> $ ./autogen.sh
> + rm -rf autom4te.cache
> + autoreconf --force --install --warnings all,no-obsolete
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 3936.
> Makefile.am:69: error: Libtool library used but 'LIBTOOL' is undefined
> Makefile.am:69:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> Makefile.am:69:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> Makefile.am:69:   If 'LT_INIT' is in 'configure.ac', make sure
> Makefile.am:69:   its definition is in aclocal's search path.
> autoreconf: automake failed with exit status: 1

even though I have installed the latest libtool package...
I'm using ubuntu 16.04

**Comment by OlafvdSpek** [comment]
Hmm. Is ctemplate available as a package?
Perhaps it's not just libtool that needs a later version.

What version of ctemplate are you using?

**Comment by cheiio** [comment]
Hi, 

I tried to compile the latest version... I managed to solve the problem by running the command 
libtoolize
Then for the ' ./autogen.sh && ./configure ' commands I used the ' CXX=g++6 ' because ubuntus default compiler is g++5 that doesnt support c++11 ... and thats it...

Thank you for your answer, I don't think this was even an issue to start with....

**Comment by OlafvdSpek** [comment]
2017-12-01 9:50 GMT+01:00 cheiio <notifications@github.com>:

> Hi,
>
> I tried to compile the latest version... I managed to solve the problem by
> running the command
> libtoolize
> Then for the ' ./autogen.sh && ./configure ' commands I used the '
> CXX=g++6 ' because ubuntus default compiler is g++5 that doesnt support
> c++11 ... and thats it...
>
> Thank you for your answer, I don't think this was even an issue to start
> with....
>
4.9 says: #error This file requires compiler and library support for the
ISO C++ 2011 standard. This support is currently experimental, and must be
enabled with the -std=c++11 or -std=gnu++11 compiler options.
6 uses c++14 mode by default

So it's an issue on older distros.
Can't remember whether the C++11 is intentional.


-- 
Olaf
