### ISSUE TITLE
Create release that supports Python 3

### ISSUE THREAD

**Issue by rillig** [OlafvdSpek/ctemplate#137]
The last CTemplate release has been in 2014. Since then the Python 3 support has been added. Is it ready for production? If so, having an official release would be nice.

Background story: [pkgsrc](https://www.pkgsrc.org) switched its default Python version to 3, therefore ctemplate doesn't build anymore by default.

**Comment by OlafvdSpek** [comment]
A release would make sense.

How does the default Python version affect ctemplate though. Is Python 2 not available anymore?

**Comment by eworm-de** [comment]
[Sunsetting Python 2](https://www.python.org/doc/sunset-python-2/)

**Comment by eworm-de** [comment]
Use this if you need to build ctemplate 2.3 with python 3.x:
[0001-python.patch](https://git.archlinux.org/svntogit/community.git/plain/trunk/0001-python.patch?h=packages/ctemplate)

**Comment by pinotree** [comment]
Note that there is a fix needed to avoid generating broken C sources.
I included that fix (incompatible with Python 2, unless more glue code is used) in my #139, can you please test it on top of ce1b8fe617bc052c1d9bf0be6000ead2fd205c6b and 4b7e6c52dc7cbb4d51c9abcebcbac91ec256a62b?

**Comment by morxa** [comment]
Fedora maintainer here: A release would also be helpful for Fedora. Fedora does not support python2 anymore, I'd need to apply the patches manually. A release would make it easier.

**Comment by OlafvdSpek** [comment]
Hi Till,
Just wondering, couldn't you use master / head?

**Comment by rillig** [comment]
> Just wondering, couldn't you use master / head?

In really obscure situations we the distributors could do that, but it's not the normal way. The normal way is that you as the author tell us "this version is ready to be shipped" by giving it a version number, and ideally some release notes. Otherwise each distributor would pick a different commit, would have to invent a version number and write the release notes themselves. Since there are several distributors (Fedora, Debian, pkgsrc, and a few others), it's better if the release is done by the author once and consistently.

**Comment by OlafvdSpek** [comment]
Makes sense, I'll create a release this week.

**Comment by OlafvdSpek** [comment]
https://github.com/OlafvdSpek/ctemplate/releases/tag/ctemplate-2.4

**Comment by pinotree** [comment]
Thanks! Uploaded to Debian :)

**Comment by eworm-de** [comment]
And thanks again, uploaded to Arch. :)

**Comment by morxa** [comment]
That was quick :) Fedora following up:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-f07f8dbc35
