### ISSUE TITLE
How to skip blank field?

### ISSUE THREAD

**Issue by AmitKGupta-git** [OlafvdSpek/ctemplate#138]
I am using the ctemplate for one of config mapping to XML output. I also wants not to print tag if value is empty/blank. 

Please can you suggest what is best way to do.

For example:
template.tpl
```
{{%AUTOESCAPE context="HTML"}}
{{#show}}
<A>
  <B>{{key}}</B>
  <C>{{value}}</C>
</A>
{{/show}}

```
if {{value}} is blank then I am getting this:
```
<A>
  <B>name</B>
  <C/>
</A>
```

But I want:
```
<A>
  <B>name</B>
</A>
```

**Comment by OlafvdSpek** [comment]
Wrap `{{value}} in a section (`{{#show_value}}`).
