### ISSUE TITLE
ctemplate-2.4 dose not has the configure file！

### ISSUE THREAD

**Issue by shiyi23** [OlafvdSpek/ctemplate#149]
Extract the .zip file or .tar.gz file，can not find configure file，and the build will failed.

**Comment by shiyi23** [comment]
[I create a PR](https://github.com/OlafvdSpek/ctemplate/pull/150)

**Comment by OlafvdSpek** [comment]
Tried `./autogen.sh`?

**Comment by shiyi23** [comment]
> Tried `./autogen.sh`?

I have tried, it will failed.

**Comment by OlafvdSpek** [comment]
Error msg?

**Comment by shiyi23** [comment]
> Error msg?

./autogen.sh is OK, but when excute the “sudo make”， will report:  make: *** No targets specified and no makefile found.  Stop.

**Comment by shiyi23** [comment]
gcc version 10.2.1;

debian WSL

**Comment by shiyi23** [comment]
> Tried `./autogen.sh`?

It's my fault, 'sudo autogen.sh' will ok, and make and make install go well.
