### ISSUE TITLE
pkg-config support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OlafvdSpek/ctemplate#15]
```
I have provided pkg-config support for ctemplate, to make it easier to
distribute and use this library in other projects.  Attached is a patch to
the build system against the current (as of 2008-05-02) repository.

I wasn't sure how to handle the _nothreads case, so I include two separate
pkgconfig entries.  Feel free to revise as you see fit.
```

Original issue reported on code.google.com by `jasta00@gmail.com` on 2 May 2008 at 11:19

Attachments:
- [ctemplate-svn-pkgconfig.patch](https://storage.googleapis.com/google-code-attachments/ctemplate/issue-15/comment-0/ctemplate-svn-pkgconfig.patch)

**Comment by kelson42** [comment]
@OlafvdSpek We need the pkg-config file (*.pc) file too... and this seems to still miss!

find . -name "*pc*" retruns no result.
